name: NPM + Node CI

on:
  push:
    branches: [main, esm-first]
  pull_request:
    branches: [main, esm-first]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16"]
        deno-version: ["1.17.2"]

    steps:
      - uses: actions/checkout@v2
      
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version}}

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: make npm
